#!/bin/sh /etc/rc.common

START=98
STOP=01

boot() {
	local enabled
	enabled="$(uci -q get dae-ui.main.version_manager_enabled)"
	[ "$enabled" = "1" ] || return 0
	/usr/libexec/dae-ui/version-boot-guard boot
}

start() {
	boot
}
